### ISSUE TITLE
Allow custom commit title/message when merge mode is "squash"

### ISSUE THREAD

**Issue by pec0ra** [reitermarkus/automerge#147]
When using `squash` as merge mode, the merge commit title is always the PR name with the PR number.
It would be great to have the possibility to customize this, for example with a new input for the action.
Similarly, it would be good if we could customize the commit message which is currently always blank.

**Comment by reitermarkus** [comment]
> possibility to customize this

How would this work? I am imagining something akin to the syntax already present in the YAML:

```yml
with:
  squash-commit-message: |
    ${pull_request.title} (#${pull_request.number})
```

**Comment by pec0ra** [comment]
@reitermarkus Thank you for your quick answer and, yes, this is what I was thinking about.

The action could use two new inputs `squash-commit-title` and `squash-commit-message` for the title and message of the commit:

 ```yaml
 with:
   squash-commit-title: |
     ${pull_request.title} (#${pull_request.number})
   squash-commit-message: |
     ${pull_request.body}
 ```
I am still wondering if this would work though since I think the `pull_request` context won't be available for all the triggers. This might be even more complicated if we want to use it with the schedule.
Do you have any idea about the feasibility of something like this?
