### ISSUE TITLE
Merge Failed

### ISSUE THREAD

**Issue by NotKyoyo** [reitermarkus/automerge#1943]
Do you have any idea why this happening? 
![image](https://user-images.githubusercontent.com/62479310/197407922-9aaf68ac-460f-4e8c-a1a3-6ddc493fe664.png)

**Comment by reitermarkus** [comment]
What's in your workflow configuration?

`pull-request-author-associations` must be one of these https://docs.github.com/en/graphql/reference/enums#commentauthorassociation.

In your case I assume you would want to set it to `OWNER`.

**Comment by NotKyoyo** [comment]
```yml
name: Automerge

on:
  # Try enabling auto-merge for all open pull requests. (Only recommended for testing.)
  push:

  # Try enabling auto-merge for all open pull requests.
  schedule:
    - cron: 0 * * * *

  # Try enabling auto-merge for a pull request when a draft is marked as “ready for review”, when
  # a required label is applied or when a “do not merge” label is removed, or when a pull request
  # is updated in any way (opened, synchronized, reopened, edited).
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: block-merge
          required-labels: hacktober-accepted
          pull-request-author-associations: NotKyoyo,kyrea
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: false
```
Here's my config.
